# Generated by Django 4.1 on 2023-01-02 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_post_comment_content_post_comment_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comment_user_name',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default=None, max_length=10)),
                ('content', models.TextField(default=None)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.post')),
            ],
        ),
    ]
